import {parseDate} from '../shared/dates.js';
import { inspector } from './registry.generated.js';
export const assets = inspector.assets;
export const fieldDefinitions = inspector.fields;
export function getAsset(id){const a=assets.find(a=>a.id===id);if(!a)throw new TypeError('Unknown asset: '+id);return a;}
const plain=v=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null);
const assertPlain=(v,name)=>{if(!plain(v))throw new TypeError(name+' must be an object');};
export const sharedKeys=Object.values(fieldDefinitions).filter(f=>!['内容','行为'].includes(f.group)&&!['width','minHeight','maxContentWidth','titleSize','artSize','gap','thickness','gradient','gradientEnd','gradientAngle','effect','hoverLift','hoverScale','intensity','motionDelay','textAlign','bubbleWidth','chatHeight','suggestionLayout','messageAppearance'].includes(f.key)).map(f=>f.key);
function validateValue(key,value){const f=fieldDefinitions[key];if(!f)throw new TypeError('Unknown field: '+key);
 if(f.type==='range'){if(typeof value!=='number'||!Number.isFinite(value)||value<f.min||value>f.max)throw new TypeError(key+' 超出允许范围');const step=f.step??1;if(Math.abs((value-f.min)/step-Math.round((value-f.min)/step))>1e-7)throw new TypeError(key+' 不符合步长');}
 else if(f.type==='boolean'){if(typeof value!=='boolean')throw new TypeError(key+' 必须为布尔值');}
 else if(f.type==='color'){if(typeof value!=='string'||!/^#[0-9a-f]{6}$/i.test(value))throw new TypeError(key+' 必须为六位十六进制颜色');}
 else if(f.type==='select'){if(!f.options.some(o=>o.value===value))throw new TypeError(key+' 无效选项');}
 else if(f.type==='text'){if(typeof value!=='string'||value.length>f.maxLength)throw new TypeError(key+' 文本过长或类型错误');}
 else if(f.type==='items'){if(!Array.isArray(value)||value.length<1||value.length>12)throw new TypeError('items 需要 1–12 个项目');const seen=new Set();for(const i of value){assertPlain(i,'item');if(Object.keys(i).some(k=>!['value','label','content','disabled'].includes(k)))throw new TypeError('item 含未支持的字段');if(typeof i.value!=='string'||!/^[a-zA-Z0-9_-]{1,50}$/.test(i.value)||seen.has(i.value))throw new TypeError('item.value 需唯一，限字母、数字、短横线');seen.add(i.value);if(typeof i.label!=='string'||i.label.length>80)throw new TypeError('item.label 无效');if(i.content!==undefined&&(typeof i.content!=='string'||i.content.length>500))throw new TypeError('item.content 无效');if(i.disabled!==undefined&&typeof i.disabled!=='boolean')throw new TypeError('item.disabled 无效');}}
 if(key==='dateValue' && value!=='' && !parseDate(value))throw new TypeError('日期必须为有效的 YYYY-MM-DD');
 return JSON.parse(JSON.stringify(value));
}
export function validateSettings(id,data={}){assertPlain(data,'settings');const allowed=getAsset(id).fields;const out={};for(const [key,value] of Object.entries(data)){if(!allowed.includes(key))throw new TypeError(id+' 不支持参数 '+key);out[key]=validateValue(key,value);}return out;}
export function validateDesignSystem(system={}){assertPlain(system,'designSystem');if(Object.keys(system).some(k=>!['global','components'].includes(k)))throw new TypeError('designSystem 字段错误');const out={global:{},components:{}};assertPlain(system.global??{},'global');for(const [key,value] of Object.entries(system.global??{})){if(!sharedKeys.includes(key))throw new TypeError('全局不支持 '+key);out.global[key]=validateValue(key,value);}assertPlain(system.components??{},'components');for(const [id,s] of Object.entries(system.components??{}))out.components[getAsset(id).id]=validateSettings(id,s);return out;}
export function resolveSettings(id,settings={},designSystem={}){const a=getAsset(id),system=validateDesignSystem(designSystem);const overrides={...Object.fromEntries(Object.entries(system.global).filter(([k])=>a.fields.includes(k))),...(system.components[id]??{}),...validateSettings(id,settings)};
 const defaults=Object.fromEntries(a.fields.map(k=>[k,JSON.parse(JSON.stringify(fieldDefinitions[k].default))]));
 if(overrides.skin==='precise')Object.assign(defaults,{radius:4,shadow:0});
 if(overrides.mode==='dark')Object.assign(defaults,{primary:'#ad9df8',foreground:'#19151f',surface:'#202029',text:'#efedf5',muted:'#34323e',border:'#4d495b'});
 return {...defaults,...a.defaults,...overrides};}
export function createPreset(asset,settings={},designSystem={}){getAsset(asset);return {schemaVersion:1,libraryVersion:'0.5.0',asset,settings:validateSettings(asset,settings),designSystem:validateDesignSystem(designSystem)};}
export function parsePreset(input){if(typeof input==='string'&&input.length>262144)throw new TypeError('配置文件过大');const p=typeof input==='string'?JSON.parse(input):input;assertPlain(p,'preset');if(p.schemaVersion!==1||!['0.2.0','0.3.0','0.4.0','0.5.0'].includes(p.libraryVersion))throw new TypeError('配置版本不兼容，需要迁移');if(Object.keys(p).some(k=>!['schemaVersion','libraryVersion','asset','settings','designSystem'].includes(k)))throw new TypeError('配置包含不支持的顶级字段');return createPreset(p.asset,p.settings,p.designSystem);}
export function settingsToTheme(s){const tokens={};const assign=(key,v)=>{if(v!==undefined)tokens[key]=String(v);};
 for(const [key,token] of [['primary','primary'],['foreground','on-primary'],['surface','surface'],['surface','field-background'],['text','text'],['muted','muted'],['border','border']])assign(token,s[key]);
 if(s.primary){assign('primary-hover',s.primary);assign('focus',s.primary);assign('primary-soft',`color-mix(in srgb, ${s.primary} 12%, ${s.surface||'#ffffff'})`);}
 if(s.radius!==undefined)for(const k of ['radius-control','radius-panel','radius-pill'])assign(k,s.radius+'px');
 if(s.fontSize!==undefined)assign('font-size',s.fontSize+'px');if(s.padding!==undefined){assign('panel-padding',s.padding+'px');assign('control-padding',s.padding+'px');}
 if(s.controlHeight!==undefined)for(const k of ['height-sm','height-md','height-lg'])assign(k,s.controlHeight+'px');
 if(s.duration!==undefined)assign('duration',s.duration+'ms');if(s.shadow!==undefined)assign('shadow',`0 ${Math.round(s.shadow/3)}px ${s.shadow*2}px rgb(20 15 50 / ${s.shadow?0.16:0})`);
 if(s.fontFamily){const families={system:'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',rounded:'ui-rounded, "SF Pro Rounded", "Nunito Sans", system-ui, sans-serif',mono:'ui-monospace, "SFMono-Regular", Consolas, monospace'};assign('font',families[s.fontFamily]||families.system);}
 return {skin:s.skin||'soft',mode:s.mode||'light',density:s.density||'comfortable',motion:s.motion!==false,tokens};}
export function cssProperties(s){const px=new Set(['fontSize','radius','padding','controlHeight','shadow','borderWidth','titleSize','gap','artSize','thickness','hoverLift','letterSpacing','minHeight','maxContentWidth','blur']);const ms=new Set(['duration','motionDelay']);const unitless=new Set(['fontWeight','lineHeight','opacity','hoverScale','intensity']);const props={};for(const k of ['fontSize','fontWeight','lineHeight','letterSpacing','radius','padding','controlHeight','shadow','borderWidth','borderStyle','titleSize','gap','artSize','thickness','hoverLift','hoverScale','duration','motionDelay','opacity','blur','minHeight','maxContentWidth','textAlign','intensity']){if(s[k]===undefined)continue;const v=s[k];props['--yk-craft-'+k]=px.has(k)?v+'px':ms.has(k)?v+'ms':unitless.has(k)?String(v):String(v);}if(s.easing){const ease={smooth:'cubic-bezier(.2,.8,.2,1)',snappy:'cubic-bezier(.2,.9,.25,1)',spring:'cubic-bezier(.2,1.35,.4,1)'};props['--yk-craft-ease']=ease[s.easing]||ease.smooth;}if(s.bubbleWidth!==undefined)props['--yk-ai-bubble-width']=s.bubbleWidth+'%';return props;}
export function toVueSFC(preset){const p=parsePreset(preset);const safe=JSON.stringify(p,null,2).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');return `<script setup>\nimport { YkAsset } from '@zhaoysg/yuankit-vue/studio'\nimport '@zhaoysg/yuankit-vue/style.css'\n\nconst preset = ${safe}\n// Connect actions to the application's router / data services.\nfunction handleAction(event) { console.log(event) }\n</script>\n\n<template>\n  <YkAsset :asset="preset.asset" :settings="preset.settings"\n    :design-system="preset.designSystem" @action="handleAction" />\n</template>\n`;}
