import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
const tokens=JSON.parse(read('packages/tokens/src/tokens.json'));
const registry=JSON.parse(read('registry/components.json'));
const inspector=JSON.parse(read('registry/inspector.json'));
write('apps/docs/src/presets.generated.js',`// Generated from registry/presets.json\nexport default ${read('registry/presets.json')};\n`);
const activeRegistry=registry.filter(c=>c.status!=='draft');
write('packages/vue/src/components.generated.js',activeRegistry.map(c=>`import { ${c.name} } from './${c.source.split('packages/vue/src/')[1]}';`).join('\n')+'\nexport const publicComponents = {'+activeRegistry.map(c=>c.name).join(',')+'};\n');
write('packages/vue/src/studio/registry.generated.js',`// Generated from registry/inspector.json. Do not edit.\nexport const inspector = ${JSON.stringify(inspector)};\n`);
write('apps/docs/src/sources.generated.js',`// Generated from references/inspiration-sources.json\nexport default ${read('references/inspiration-sources.json')};\n`);
const declaration=(selector,values)=>`${selector} {\n${Object.entries(values).map(([k,v])=>`  --yk-${k}: ${v};`).join('\n')}\n}\n`;
let css=declaration('.yk-theme',tokens.base);
for(const [category,attribute] of [['modes','mode'],['skins','skin'],['densities','density']]){
 for(const [name,values] of Object.entries(tokens[category]))css+=declaration(`.yk-theme[data-yk-${attribute}="${name}"]`,values);
}
const keys=[...new Set([Object.keys(tokens.base),...['modes','skins','densities'].flatMap(c=>Object.values(tokens[c]).map(Object.keys))].flat())].sort();
write('packages/vue/src/config/token-keys.js',`// Generated by scripts/build.mjs from tokens.json. Do not edit.\nexport const tokenKeys = ${JSON.stringify(keys)};\n`);
let theme=read('packages/vue/src/config/theme.js');
theme=theme.replace(/^export const tokenKeys = [^\n]+;\n/,"import { tokenKeys } from './token-keys.js';\nexport { tokenKeys } from './token-keys.js';\n");
write('packages/vue/src/config/theme.js',theme);
const publicTypes=read('packages/vue/src/types.d.ts').replace(/^export type TokenName = [^\n]+;/m,`export type TokenName = ${keys.map(k=>JSON.stringify(k)).join(' | ')};`);
write('packages/vue/src/types.d.ts',publicTypes);
write('apps/docs/src/registry.generated.js',`// Generated from registry/components.json\nexport default ${JSON.stringify(registry)};\n`);
for(const pkg of ['tokens','vue']){
 const out=path.join(root,`packages/${pkg}/dist`);fs.rmSync(out,{recursive:true,force:true});
 fs.cpSync(path.join(root,`packages/${pkg}/src`),out,{recursive:true,filter:source=>!source.endsWith('README.md')&&!registry.filter(c=>c.status==='draft').some(c=>source===path.join(root,`packages/vue/src/components/${c.id}`)||source.startsWith(path.join(root,`packages/vue/src/components/${c.id}`)+path.sep))});
}
write('packages/tokens/dist/style.css',css);
const styles=registry.filter(x=>x.status!=='draft').map(x=>read(x.style)).join('\n');
const uiCss=css+'\n'+read('packages/vue/src/base.css')+'\n'+styles+'\n'+read('packages/vue/src/blocks/style.css')+'\n'+read('packages/vue/src/blocks/ai.css')+'\n'+read('packages/vue/src/effects/style.css')+'\n'+read('packages/vue/src/studio/style.css');
write('packages/vue/dist/style.css',uiCss);
/** Build the offline/global artifacts from the SAME source modules as the ESM package.
 * TypeScript's parser/emit handles ESM syntax, not a regex source-code rewriter.
 * Only static imports are supported by this intentionally small demo bundler.
 * The published package preserves ESM for the application's bundler and tree shaking.
 */
function bundle(entry, assign){
 const modules=new Map();
 const visit=id=>{
  if(modules.has(id))return;modules.set(id,null);
  const source=read(id);const ast=ts.createSourceFile(id,source,ts.ScriptTarget.ES2022,true,ts.ScriptKind.JS);
  const deps={};
  for(const node of ast.statements){
   if((ts.isImportDeclaration(node)||ts.isExportDeclaration(node))&&node.moduleSpecifier){
    const spec=node.moduleSpecifier.text;
    if(spec==='vue'){deps[spec]='vue';continue;}
    if(!spec.startsWith('.'))throw Error(`Unsupported external dependency '${spec}' in ${id}; add an explicit adapter.`);
    const target=path.posix.normalize(path.posix.join(path.posix.dirname(id),spec));
    if(!target.endsWith('.js'))throw Error(`Use explicit .js imports: ${id} -> ${spec}`);
    deps[spec]=target;visit(target);
   }
  }
  const result=ts.transpileModule(source,{fileName:id,reportDiagnostics:true,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,allowJs:true}});
  const errors=(result.diagnostics||[]).filter(x=>x.category===ts.DiagnosticCategory.Error);
  if(errors.length)throw Error(ts.formatDiagnosticsWithColorAndContext(errors,{getCanonicalFileName:x=>x,getCurrentDirectory:()=>root,getNewLine:()=>"\n"}));
  modules.set(id,{code:result.outputText,deps});
 };
 visit(entry);
 const definitions=[...modules.entries()].map(([id,m])=>`${JSON.stringify(id)}:[function(module,exports,require){\n${m.code}\n},${JSON.stringify(m.deps)}]`).join(',\n');
 return `/* YuanKit v0.5.0 — MIT; Vue is an external dependency. */\n(function(global){'use strict';\nconst modules={${definitions}};\nconst cache={};\nfunction load(id){if(id==='vue')return global.Vue;if(cache[id])return cache[id].exports;const spec=modules[id];if(!spec)throw Error('Unknown module '+id);const module=cache[id]={exports:{}};spec[0](module,module.exports,key=>load(spec[1][key]));return module.exports;}\n${assign?`global.${assign}=`:''}load(${JSON.stringify(entry)});\n})(globalThis);\n`;
}
const library=bundle('packages/vue/src/index.js','YuanKit');
write('packages/vue/dist/yuankit.global.js',library);
write('packages/vue/dist/yuankit-studio.global.js',bundle('packages/vue/src/studio/index.js','YuanKitStudio'));
const vue=read('vendor/vue-3.5.13.global.prod.js');
if(!vue.includes('vue v3.5.13'))throw Error('Unexpected demo Vue runtime; update provenance and tests before changing it.');
const runtimeHash=crypto.createHash('sha256').update(vue).digest('hex');
write('vendor/runtime-integrity.json',JSON.stringify({version:'3.5.13',sha256:runtimeHash,license:'MIT',file:'vue-3.5.13.global.prod.js'},null,2)+'\n');
if(fs.existsSync(path.join(root,'apps/docs/src/app.js'))){
 const app=bundle('apps/docs/src/app.js');const docCss=read('blocks/style.css')+'\n'+read('apps/docs/src/docs.css')+'\n'+read('apps/docs/src/studio.css');
 write('apps/docs/app.bundle.js',app);write('apps/docs/styles.css',uiCss+'\n'+docCss);
 const head='<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>YuanKit · 元件库</title><meta name="description" content="自己的 Vue 组件、主题与方案资产库"></head>';
 const body='<body><div id="app"></div><noscript>请启用 JavaScript 查看组件库演示。</noscript>';
 write('apps/docs/index.html',head.replace('</head>','<link rel="stylesheet" href="styles.css"></head>')+body+'<script src="../../vendor/vue-3.5.13.global.prod.js"></script><script src="app.bundle.js"></script></body></html>');
 const safe=s=>s.replace(/<\/script/gi,'<\\/script');
 const offline=head.replace('</head>',`<style>${uiCss}\n${docCss}</style></head>`)+body+`<script>${safe(vue)}</script><script>${safe(app)}</script></body></html>`;
 write('preview.html',offline);
 write('preview-ai.html',offline.replace('<body>','<body><script>if(!location.hash)location.hash="studio/ai-chat-page";</script>'));
}
write('tests/browser/fixture.html','<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>YuanKit contract tests</title><link rel="stylesheet" href="../../packages/vue/dist/style.css"><style>body{margin:32px}#fixture{max-width:900px}</style></head><body><div id="fixture"></div><script src="../../vendor/vue-3.5.13.global.prod.js"></script><script src="../../packages/vue/dist/yuankit.global.js"></script></body></html>');
write('reports/build.json',JSON.stringify({builtAt:new Date().toISOString(),version:'0.5.0',components:registry.filter(x=>x.status!=='draft').length,cssBytes:Buffer.byteLength(uiCss),globalJsBytes:Buffer.byteLength(library),vueIncludedInNpmPackage:false,demoVueVersion:'3.5.13',demoVueSha256:runtimeHash,typescriptSyntaxEmit:true,fullVueTypeCheck:false},null,2)+'\n');
console.log(`Built ${registry.filter(x=>x.status!=='draft').length} Vue exports; ESM + CSS + global + offline workbench.`);
