import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { clamp, contrastRatio, foregroundFor } from '../../packages/tokens/src/index.js';
import { defaultConfig } from '../../packages/vue/src/config/defaults.js';
import { mergeConfig, toCssVariables, themeAttrs, tokenKeys } from '../../packages/vue/src/config/theme.js';
import { createComponent } from '../../scripts/new-component.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const registry = JSON.parse(read('registry/components.json'));
test('clamp bounds and non-finite input', () => { assert.equal(clamp(-2), 0); assert.equal(clamp(102), 100); assert.equal(clamp(NaN), 0); assert.equal(clamp('42'), 42); });
test('contrast black/white and symmetry', () => { assert.equal(contrastRatio('#000000', '#ffffff'), 21); assert.equal(contrastRatio('#ffffff', '#000000'), 21); assert.equal(contrastRatio('#aaaaaa', '#aaaaaa'), 1); });
test('contrast rejects unsupported color syntaxes', () => { for (const value of ['red', '#fff', '#ffffff00', 'invalid']) assert.throws(() => contrastRatio(value, '#ffffff'), TypeError); });
test('foreground selects readable primary label', () => { for (const bg of ['#5b45d6', '#a99afb', '#22ff11']) assert.ok(contrastRatio(bg, foregroundFor(bg)) >= 4.5); });
test('default palette normal text and key status labels reach 4.5:1', () => { const tokens = JSON.parse(read('packages/tokens/src/tokens.json')); for (const mode of Object.values(tokens.modes)) { for (const [a, b] of [['text', 'surface'], ['text-muted', 'surface'], ['on-primary', 'primary']]) assert.ok(contrastRatio(mode[a], mode[b]) >= 4.5, `${a}/${b}`); } });
test('configuration precedence and inheritance', () => { const parent = mergeConfig(defaultConfig, { mode: 'dark', tokens: { primary: '#000000' } }); const child = mergeConfig(parent, { size: 'sm', tokens: { 'radius-control': '8px' } }); assert.equal(child.mode, 'dark'); assert.equal(child.size, 'sm'); assert.equal(child.tokens.primary, '#000000'); assert.equal(parent.size, 'md'); });
test('undefined does not erase defaults', () => assert.equal(mergeConfig(defaultConfig, { size: undefined }).size, 'md'));
test('invalid configuration enums are rejected', () => { for (const data of [{ mode: 'pink' }, { skin: 'antd' }, { density: 'none' }, { size: 'xl' }, { locale: 'xx' }, { motion: 'yes' }]) assert.throws(() => mergeConfig(defaultConfig, data), TypeError); });
test('token allowlist rejects typos and declaration injection', () => { assert.throws(() => toCssVariables({ typo: 'red' }), TypeError); assert.throws(() => toCssVariables({ primary: 'red;display:none' }), TypeError); assert.throws(() => toCssVariables({ primary: 4 }), TypeError); assert.deepEqual(toCssVariables({ primary: 'var(--brand)' }), { '--yk-primary': 'var(--brand)' }); });
test('theme attrs include local motion override', () => { const x = themeAttrs(mergeConfig(defaultConfig, { motion: false })); assert.equal(x['data-yk-motion'], 'false'); assert.equal(x.style['--yk-duration'], '0ms'); });
test('every public component has source styles types and four-dimensional spec', () => { const exports = read('packages/vue/src/index.js'); for (const c of registry.filter(c => c.status !== 'draft')) { for (const p of [c.source, c.style, c.types, c.spec]) assert.ok(fs.existsSync(path.join(root, p)), p); assert.ok(exports.includes(c.name), c.name); assert.ok(c.rules.length && c.visual && c.structure && c.limitations.length); assert.ok(c.references.length); } });
test('registry identifiers unique', () => { assert.equal(new Set(registry.map(c => c.id)).size, registry.length); assert.equal(new Set(registry.map(c => c.name)).size, registry.length); });
test('exported token names are generated from the source of truth', () => { const data = JSON.parse(read('packages/tokens/src/tokens.json')); const actual = new Set([...Object.keys(data.base), ...['modes', 'skins', 'densities'].flatMap(k => Object.values(data[k]).flatMap(Object.keys))]); assert.deepEqual([...actual].sort(), tokenKeys); });
test('package runtime is external Vue, not React or copied upstream runtime', () => { const pkg = JSON.parse(read('packages/vue/package.json')); assert.equal(pkg.peerDependencies.vue, '>=3.5.13 <4'); assert.ok(!pkg.dependencies); assert.ok(!read('packages/vue/dist/yuankit.global.js').includes('vue v3.5.13')); assert.ok(!read('packages/vue/dist/index.js').includes('react')); assert.ok(read('packages/vue/dist/style.css').includes('.yk-button')); });
test('component scaffolder writes a draft, not a public export', () => { const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'yuankit-test-')); try { fs.mkdirSync(path.join(tmp, 'registry')); fs.writeFileSync(path.join(tmp, 'registry/components.json'), '[]'); const out = createComponent(tmp, 'empty-state'); assert.equal(out.name, 'YkEmptyState'); assert.equal(JSON.parse(fs.readFileSync(path.join(tmp, 'registry/components.json')))[0].status, 'draft'); assert.ok(fs.existsSync(path.join(tmp, out.directory, 'index.d.ts'))); assert.throws(() => createComponent(tmp, 'empty-state')); assert.throws(() => createComponent(tmp, '../bad')); assert.throws(() => createComponent(tmp, 'Invalid')); } finally { fs.rmSync(tmp, { recursive: true, force: true }); } });
